// This file is auto-generated by @hey-api/openapi-ts

export const TestPlanSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'Name of the test plan'
        },
        id: {
            type: 'string',
            description: 'Unique identifier for the test plan'
        },
        modules: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    testModule: {
                        type: 'string'
                    },
                    instances: {
                        type: 'array',
                        items: {
                            type: 'string'
                        }
                    }
                }
            }
        }
    }
} as const;

export const PaginationRequestSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            description: 'Page number (0-based)'
        },
        size: {
            type: 'integer',
            description: 'Number of items per page'
        }
    }
} as const;

export const TestLogSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        testName: {
            type: 'string'
        },
        variant: {
            type: 'object'
        },
        results: {
            type: 'array',
            items: {
                type: 'object'
            }
        }
    }
} as const;

export const JWKSetSchema = {
    type: 'object',
    properties: {
        keys: {
            type: 'array',
            items: {
                type: 'object',
                description: 'JSON Web Key'
            }
        }
    }
} as const;